name: party_finder_app_flutter_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.0.4
  file_picker: ^8.1.7 
  intl: ^0.18.1 # For date formatting
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets: 
    - assets/images/masterOfDirtPicture.jpg
    - .env
  uses-material-design: true
